modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="all_the_gear"
version="1.0.0"
displayName="all the gear"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="mlaro, MCreator"

[[dependencies.all_the_gear]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




